name: 'check-version-before-release'
description: 'Asserts that package-lock.json and package.json version is the same and that it is the same or higher than the latest published tag in repo.'
author: 'Digital Catapult'
inputs:
  npm_package_location:
    required: true
    description: 'path to files'
    default: './'
  token:
    description: 'The token to use to access the GitHub API'
    required: true
outputs:
  is_new_version:
    description: 'boolean indicating if this is a new version true = yes '
  version:
    description: 'current version'
  build_date:
    description: 'date of the build'
  is_prerelease:
    description: 'boolean indicating if this is a prerelease true = yes '

runs:
  using: 'node16'
  main: 'dist/index.js'
