name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  location:
    required: true
    description: 'path to files'
    default: './'
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'composite'
  steps:
    - run: echo some location ${{inputs.location}}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
