name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  location:
    required: true
    description: 'path to files'
    default: './'
  # owner:
  #   description: 'The owner of the repository'
  #   required: true
  # repo:
  #   description: 'The name of the repository'
  #   required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true

  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'lib/main.js'
  # steps:
  #   - run: echo some location ${{inputs.location}}
  #     shell: bash
  #   - run: echo some owner ${{inputs.owner}}
  #     shell: bash
  #   - run: echo some repo ${{inputs.repo}}
  #     shell: bash
  #   - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
  #     shell: bash
  #   - run: echo goodbye ====
  #     shell: bash
